### ISSUE TITLE
windows character bug when running sbt

### ISSUE THREAD

**Issue by er1c** [47degrees/sbt-microsites#488]
```
[debug]         C:\Users\eric\Documents\GitHub\scala-typesafeequals\core\src\main\scala\typesafeequals\package.scala
[info] Main Scala API documentation successful.
[debug] Checking for meta build source updates
[error] java.lang.IllegalArgumentException: character to be escaped is missing
[error]         at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020)
[error]         at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
[error]         at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1182)
```

It happens when running `sbt ci-doc` on https://github.com/er1c/scala-typesafeequals

Full stacktrace: https://gist.github.com/er1c/3b363110bcd69a6b5e1603f7179bba68

**Comment by er1c** [comment]
Looks like I still get the same exception even with `set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` and `chcp 65001`

**Comment by er1c** [comment]
This is the likely culprit, it looks like the author tried to do the right thing, but `replaceAll` uses regex instead of literally.

**Comment by artemkorsakov** [comment]
I have the same problem!
