### ISSUE TITLE
Weird DirectoryNotEmptyException when running makeMicrosite

### ISSUE THREAD

**Issue by alexandru** [47degrees/sbt-microsites#613]
I'm getting an exception when running `makeMicrosite`, not sure if it matters or not...

```
root(main)> site/makeMicrosite
Copying resources from sbt-microsite JAR
java.nio.file.DirectoryNotEmptyException: .../site/target/scala-2.13/resource_managed/main/jekyll/_sass
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:247)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1180)
	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:117)
	at java.base/java.nio.file.Files.copy(Files.java:1297)
	at microsites.ioops.FileWriter.$anonfun$copyResourcesFromFileSystem$3(FileWriter.scala:105)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
	at microsites.ioops.FileWriter.$anonfun$copyResourcesFromFileSystem$2(FileWriter.scala:102)
	at microsites.ioops.FileWriter.$anonfun$copyResourcesFromFileSystem$2$adapted(FileWriter.scala:99)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at microsites.ioops.FileWriter.$anonfun$copyResourcesFromFileSystem$1(FileWriter.scala:99)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:370)
	at microsites.ioops.FileWriter.copyResourcesFromFileSystem(FileWriter.scala:99)
	at microsites.util.MicrositeHelper.copyResources(MicrositeHelper.scala:69)
	at microsites.util.MicrositeHelper.createResources(MicrositeHelper.scala:111)
	at microsites.MicrositeAutoImportSettings.$anonfun$micrositeTasksSettings$1(MicrositeKeys.scala:402)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[warn] Compile / run / javaOptions will be ignored, Compile / run / fork is set to false
[info] running mdoc.Main
info: Compiling 1 file to /Users/wp79lh/Projects/monix/newtypes/site/target/scala-2.13/resource_managed/main/jekyll
info: Compiled in 1.98s (0 errors)
...
```

**Comment by juanpedromoreno** [comment]
Hey @alexandru , definitely it's a weird issue. Unfortunately, that repo is 404 for me, so I cannot give it a try. Please, let me know if I can reproduce the issue somewhere else. Thanks!
